variables:
  DOCKER_DRIVER: overlay2

build-api:
  stage: build
  services:
    - docker:dind
  image: docker:latest
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - cd ./API
    - docker build -t "$CI_REGISTRY_IMAGE:latest" . -f Dockerfile
    - docker push "$CI_REGISTRY_IMAGE:latest"
